### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by rasmus-bjoern** [known-as-bmf/react-signalr#2]
Hi, 

Thanks for this :)

I have a small issue, when I run everything localhost all runs smooth and no hassel.

After deployment I get this error:

TypeError: Object(...) is not a function
    at react-signalr.esm.js:211
    at CriminalRecordInfo.js:34
    at ss (react-dom.production.min.js:5142)
    at kl (react-dom.production.min.js:6494)
    at t.unstable_runWithPriority (scheduler.production.min.js:309)
    at Go (react-dom.production.min.js:2816)
    at Sl (react-dom.production.min.js:6474)
    at ul (react-dom.production.min.js:5870)
    at react-dom.production.min.js:2851
    at t.unstable_runWithPriority (scheduler.production.min.js:309)

If I Chrome debug i think this is the breaking point - I tried looking through code to se what's up, but no luck.

react-signalr.esm.js (Breaks in this file)
return fromEventPattern(sub, unsub); (This line)

Im using the hook like this: (Edit out names for security)

 useEffect(() => {
        const letterStatus = on("METHODNAME").pipe(debounceTime(200)).subscribe(useStateSetMethod);
 return () => letterStatus.unsubscribe();
    }, [on])

**Comment by known-as-bmf** [comment]
Hello and thank you for the feedback !

I quickly looked into it and my guess is that the `fromEventPattern` import isn't working properly...

Would you happen to use a different tsconfig / rxjs version for your dev and prod environments ?

**Comment by rasmus-bjoern** [comment]
Hi again, I use the same tsconfig and same version.
This is my tsconfig:

{
  "compilerOptions": {
    "noImplicitAny": true,
    "target": "es5",
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve",
    "lib": ["es2019", "dom"],
    "typeRoots": ["./typings", "./node_modules/@types"],
    "types": ["node"]
  },
  "include": ["src/**/*", "typings/**/*"]
}

**Comment by known-as-bmf** [comment]
Hmmmm I'm using the lib on a project with a configuration similar to this with no issue

only difference is the `lib` option, I'm using:

```json
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
```

but I don't think changing that will resolve your problem.

Which typescript version are you using ?

**Comment by known-as-bmf** [comment]
interesting related link https://github.com/facebook/react/issues/14484#issuecomment-474345221

**Comment by rasmus-bjoern** [comment]
Ehm. Okay, so a little embarrassing, but it seems like I didn't install rxjs 🤦 
Installing and queuing and new build now, will share result 😄

**Comment by rasmus-bjoern** [comment]
So all good, was missing rxjs and rxjs-compat 😅 
Sorry for the inconvenience.

**Comment by known-as-bmf** [comment]
No problem at all :)

Also, you shouldn't need `rxjs-compat` if you're already using rxjs@6 or newer.
